### ISSUE TITLE
i am new using eq and your web is a blessing but i need you to read the description plis

### ISSUE THREAD

**Issue by KthanidKisure** [Shewiiii/webEQ#1]
so i bought the new iems Simgot Supermix 4 and they are amazinggggggg, 4 drivers well tuned for the harman target, I would like to ask if you could add the supermix 4 to your page so I can use the eq to the harman beta 2024 target, thanks for your time and hard work.

**Comment by Shewiiii** [comment]
Hi! Sorry for the late reply, I didn't think anyone would actually use my website lol.
However, it seems that no measurements of the Simgot Supermix 4 taken with the 5128 are available currently.
What you can do however, is use this target:
[Δ Harman Beta (2024).txt](https://github.com/user-attachments/files/15826549/Harman.Beta.2024.txt)
Import it, and autoEQ on this squiglink (in the equalizer tab):
https://pw.squig.link/?share=Simgot_Supermix_4

It's basically a delta target: I took the compensation Listener made (the average difference in measured frequency between the 711 coupler and the B&K 5128) and applied it to Harman Beta.
It's far from 100% accurate but your EQ should be pretty similar.

If you have any other questions, don't hesitate!
